///v1/users/{username}/top-repos, but acting as if I can access all users this way
export const PRData = {
  "data": [
    {
      "id": 71359796,
      "user_id": 1,
      "size": 274322,
      "node_id": "MDEwOlJlcG9zaXRvcnk3MTM1OTc5Ng==",
      "git_url": "git://github.com/open-sauced/insights.git",
      "ssh_url": "git@github.com:open-sauced/insights.git",
      "clone_url": "https://github.com/open-sauced/insights.git",
      "svn_url": "https://github.com/open-sauced/insights",
      "mirror_url": null,
      "name": "open-sauced",
      "full_name": "open-sauced/insights",
      "description": "🍕This is a project to identify your next open source contribution! 🍕",
      "language": "JavaScript",
      "license": "MIT",
      "url": "https://api.github.com/repos/open-sauced/insights",
      "homepage": "https://app.opensauced.pizza",
      "topics": [
        "open-sauced",
        "open-source",
        "github"
      ],
      "open_prs_count": 5,
      "closed_prs_count": 173,
      "merged_prs_count": 27,
      "draft_prs_count": 2,
      "spam_prs_count": 2,
      "pr_velocity_count": 0,
      "pr_active_count": 0
    },
    {
      "id": 713597965,
      "user_id": 2,
      "size": 274322,
      "node_id": "MDEwOlJlcG9zaXRvcnk3MTM1OTc5Ng==",
      "git_url": "git://github.com/open-sauced/insights.git",
      "ssh_url": "git@github.com:open-sauced/insights.git",
      "clone_url": "https://github.com/open-sauced/insights.git",
      "svn_url": "https://github.com/open-sauced/insights",
      "mirror_url": null,
      "name": "open-sauced",
      "full_name": "open-sauced/insights",
      "description": "🍕This is a project to identify your next open source contribution! 🍕",
      "language": "JavaScript",
      "license": "MIT",
      "url": "https://api.github.com/repos/open-sauced/insights",
      "homepage": "https://app.opensauced.pizza",
      "topics": [
        "open-sauced",
        "open-source",
        "github"
      ],
      "open_prs_count": 5,
      "closed_prs_count": 173,
      "merged_prs_count": 2726,
      "draft_prs_count": 2,
      "spam_prs_count": 2,
      "pr_velocity_count": 0,
      "pr_active_count": 0
    },
    {
      "id": 713597966,
      "user_id": 3,
      "size": 274322,
      "node_id": "MDEwOlJlcG9zaXRvcnk3MTM1OTc5Ng==",
      "git_url": "git://github.com/open-sauced/insights.git",
      "ssh_url": "git@github.com:open-sauced/insights.git",
      "clone_url": "https://github.com/open-sauced/insights.git",
      "svn_url": "https://github.com/open-sauced/insights",
      "mirror_url": null,
      "name": "open-sauced",
      "full_name": "open-sauced/insights",
      "description": "🍕This is a project to identify your next open source contribution! 🍕",
      "language": "JavaScript",
      "license": "MIT",
      "url": "https://api.github.com/repos/open-sauced/insights",
      "homepage": "https://app.opensauced.pizza",
      "topics": [
        "open-sauced",
        "open-source",
        "github"
      ],
      "open_prs_count": 5,
      "closed_prs_count": 173,
      "merged_prs_count": 6,
      "draft_prs_count": 2,
      "spam_prs_count": 2,
      "pr_velocity_count": 0,
      "pr_active_count": 0
    },
    {
      "id": 713597967,
      "user_id": 4,
      "size": 274322,
      "node_id": "MDEwOlJlcG9zaXRvcnk3MTM1OTc5Ng==",
      "git_url": "git://github.com/open-sauced/insights.git",
      "ssh_url": "git@github.com:open-sauced/insights.git",
      "clone_url": "https://github.com/open-sauced/insights.git",
      "svn_url": "https://github.com/open-sauced/insights",
      "mirror_url": null,
      "name": "open-sauced",
      "full_name": "open-sauced/insights",
      "description": "🍕This is a project to identify your next open source contribution! 🍕",
      "language": "JavaScript",
      "license": "MIT",
      "url": "https://api.github.com/repos/open-sauced/insights",
      "homepage": "https://app.opensauced.pizza",
      "topics": [
        "open-sauced",
        "open-source",
        "github"
      ],
      "open_prs_count": 5,
      "closed_prs_count": 173,
      "merged_prs_count": 1,
      "draft_prs_count": 2,
      "spam_prs_count": 2,
      "pr_velocity_count": 0,
      "pr_active_count": 0
    },
    {
      "id": 713597968,
      "user_id": 5,
      "size": 274322,
      "node_id": "MDEwOlJlcG9zaXRvcnk3MTM1OTc5Ng==",
      "git_url": "git://github.com/open-sauced/insights.git",
      "ssh_url": "git@github.com:open-sauced/insights.git",
      "clone_url": "https://github.com/open-sauced/insights.git",
      "svn_url": "https://github.com/open-sauced/insights",
      "mirror_url": null,
      "name": "open-sauced",
      "full_name": "open-sauced/insights",
      "description": "🍕This is a project to identify your next open source contribution! 🍕",
      "language": "JavaScript",
      "license": "MIT",
      "url": "https://api.github.com/repos/open-sauced/insights",
      "homepage": "https://app.opensauced.pizza",
      "topics": [
        "open-sauced",
        "open-source",
        "github"
      ],
      "open_prs_count": 5,
      "closed_prs_count": 173,
      "merged_prs_count": 26,
      "draft_prs_count": 2,
      "spam_prs_count": 2,
      "pr_velocity_count": 0,
      "pr_active_count": 0
    },
    {
      "id": 713597968,
      "user_id": 6,
      "size": 274322,
      "node_id": "MDEwOlJlcG9zaXRvcnk3MTM1OTc5Ng==",
      "git_url": "git://github.com/open-sauced/insights.git",
      "ssh_url": "git@github.com:open-sauced/insights.git",
      "clone_url": "https://github.com/open-sauced/insights.git",
      "svn_url": "https://github.com/open-sauced/insights",
      "mirror_url": null,
      "name": "open-sauced",
      "full_name": "open-sauced/insights",
      "description": "🍕This is a project to identify your next open source contribution! 🍕",
      "language": "JavaScript",
      "license": "MIT",
      "url": "https://api.github.com/repos/open-sauced/insights",
      "homepage": "https://app.opensauced.pizza",
      "topics": [
        "open-sauced",
        "open-source",
        "github"
      ],
      "open_prs_count": 5,
      "closed_prs_count": 173,
      "merged_prs_count": 12,
      "draft_prs_count": 2,
      "spam_prs_count": 2,
      "pr_velocity_count": 0,
      "pr_active_count": 0
    }
  ],
}

///v1/users/{username} acting as if I can access all users this way
export const UserData = {
  "data": [
    {
      "id": 1,
      "open_issues": 498,
      "created_at": "2016-10-19 13:24:51.000000",
      "updated_at": "2022-08-28 22:04:29.000000",
      "first_opened_pr_at": "2022-08-28 22:04:29.000000",
      "first_pushed_commit_at": "2022-08-28 22:04:29.000000",
      "connected_at": "2022-08-28 22:04:29.000000",
      "campaign_start_date": "2022-08-28 22:04:29.000000",
      "node_id": "MDQ6VXNlcjIzNzEzMw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/237133?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/0-vortex",
      "login": "0-vortex",
      "email": "hello@opensauced.pizza",
      "is_private": false,
      "is_open_sauced_member": false,
      "is_onboarded": false,
      "is_waitlisted": false,
      "role": 10,
      "bio": "OpenSauced User",
      "blog": "https://opensauced.pizza/blog",
      "name": "MrPizza",
      "twitter_username": "saucedopen",
      "linkedin_url": "https://www.linkedin.com/in/brianldouglas",
      "github_sponsors_url": "https://github.com/sponsors/open-sauced",
      "discord_url": "https://discord.gg/opensauced",
      "company": "OpenSauced",
      "location": "San Francisco, CA",
      "display_local_time": false,
      "interests": "javascript",
      "hireable": false,
      "public_repos": 0,
      "public_gists": 0,
      "followers": 0,
      "following": 0,
      "type": "User",
      "display_email": false,
      "receive_collaboration": false,
      "receive_product_updates": false,
      "timezone": "UTC-5",
      "coupon_code": "saucy",
      "languages": "{ TypeScript: 33128, HTML: 453, JavaScript: 90, CSS: 80 }",
      "notification_count": 0,
      "insights_count": 0,
      "highlights_count": 0,
      "following_count": 0,
      "followers_count": 0,
      "recent_pull_requests_count": 0,
      "recent_pull_request_velocity_count": 0,
      "is_maintainer": true
    },
    {
      "id": 237133,
      "open_issues": 498,
      "created_at": "2016-10-19 13:24:51.000000",
      "updated_at": "2022-08-28 22:04:29.000000",
      "first_opened_pr_at": "2022-08-28 22:04:29.000000",
      "first_pushed_commit_at": "2022-08-28 22:04:29.000000",
      "connected_at": "2022-08-28 22:04:29.000000",
      "campaign_start_date": "2022-08-28 22:04:29.000000",
      "node_id": "MDQ6VXNlcjIzNzEzMw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/237133?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/0-vortex",
      "login": "0-vortex",
      "email": "hello@opensauced.pizza",
      "is_private": false,
      "is_open_sauced_member": false,
      "is_onboarded": false,
      "is_waitlisted": false,
      "role": 10,
      "bio": "OpenSauced User",
      "blog": "https://opensauced.pizza/blog",
      "name": "MrPizza",
      "twitter_username": "saucedopen",
      "linkedin_url": "https://www.linkedin.com/in/brianldouglas",
      "github_sponsors_url": "https://github.com/sponsors/open-sauced",
      "discord_url": "https://discord.gg/opensauced",
      "company": "OpenSauced",
      "location": "San Francisco, CA",
      "display_local_time": false,
      "interests": "javascript",
      "hireable": false,
      "public_repos": 0,
      "public_gists": 0,
      "followers": 0,
      "following": 0,
      "type": "User",
      "display_email": false,
      "receive_collaboration": false,
      "receive_product_updates": false,
      "timezone": "UTC-5",
      "coupon_code": "saucy",
      "languages": "{ TypeScript: 33128, HTML: 453, JavaScript: 90, CSS: 80 }",
      "notification_count": 0,
      "insights_count": 0,
      "highlights_count": 0,
      "following_count": 0,
      "followers_count": 0,
      "recent_pull_requests_count": 0,
      "recent_pull_request_velocity_count": 0,
      "is_maintainer": true
    },
    {
      "id": 2,
      "open_issues": 498,
      "created_at": "2016-10-19 13:24:51.000000",
      "updated_at": "2022-08-28 22:04:29.000000",
      "first_opened_pr_at": "2022-08-28 22:04:29.000000",
      "first_pushed_commit_at": "2022-08-28 22:04:29.000000",
      "connected_at": "2022-08-28 22:04:29.000000",
      "campaign_start_date": "2022-08-28 22:04:29.000000",
      "node_id": "MDQ6VXNlcjIzNzEzMw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/237133?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/0-vortex",
      "login": "0-vortex",
      "email": "hello@opensauced.pizza",
      "is_private": false,
      "is_open_sauced_member": false,
      "is_onboarded": false,
      "is_waitlisted": false,
      "role": 10,
      "bio": "OpenSauced User",
      "blog": "https://opensauced.pizza/blog",
      "name": "MrPizza",
      "twitter_username": "saucedopen",
      "linkedin_url": "https://www.linkedin.com/in/brianldouglas",
      "github_sponsors_url": "https://github.com/sponsors/open-sauced",
      "discord_url": "https://discord.gg/opensauced",
      "company": "OpenSauced",
      "location": "San Francisco, CA",
      "display_local_time": false,
      "interests": "javascript",
      "hireable": false,
      "public_repos": 0,
      "public_gists": 0,
      "followers": 0,
      "following": 0,
      "type": "User",
      "display_email": false,
      "receive_collaboration": false,
      "receive_product_updates": false,
      "timezone": "UTC-5",
      "coupon_code": "saucy",
      "languages": "{ TypeScript: 33128, HTML: 453, JavaScript: 90, CSS: 80 }",
      "notification_count": 0,
      "insights_count": 0,
      "highlights_count": 0,
      "following_count": 0,
      "followers_count": 0,
      "recent_pull_requests_count": 0,
      "recent_pull_request_velocity_count": 0,
      "is_maintainer": true
    },
    {
      "id": 3,
      "open_issues": 498,
      "created_at": "2016-10-19 13:24:51.000000",
      "updated_at": "2022-08-28 22:04:29.000000",
      "first_opened_pr_at": "2022-08-28 22:04:29.000000",
      "first_pushed_commit_at": "2022-08-28 22:04:29.000000",
      "connected_at": "2022-08-28 22:04:29.000000",
      "campaign_start_date": "2022-08-28 22:04:29.000000",
      "node_id": "MDQ6VXNlcjIzNzEzMw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/237133?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/0-vortex",
      "login": "0-vortex",
      "email": "hello@opensauced.pizza",
      "is_private": false,
      "is_open_sauced_member": false,
      "is_onboarded": false,
      "is_waitlisted": false,
      "role": 10,
      "bio": "OpenSauced User",
      "blog": "https://opensauced.pizza/blog",
      "name": "MrPizza",
      "twitter_username": "saucedopen",
      "linkedin_url": "https://www.linkedin.com/in/brianldouglas",
      "github_sponsors_url": "https://github.com/sponsors/open-sauced",
      "discord_url": "https://discord.gg/opensauced",
      "company": "OpenSauced",
      "location": "San Francisco, CA",
      "display_local_time": false,
      "interests": "javascript",
      "hireable": false,
      "public_repos": 0,
      "public_gists": 0,
      "followers": 0,
      "following": 0,
      "type": "User",
      "display_email": false,
      "receive_collaboration": false,
      "receive_product_updates": false,
      "timezone": "UTC-5",
      "coupon_code": "saucy",
      "languages": "{ TypeScript: 33128, HTML: 453, JavaScript: 90, CSS: 80 }",
      "notification_count": 0,
      "insights_count": 0,
      "highlights_count": 0,
      "following_count": 0,
      "followers_count": 0,
      "recent_pull_requests_count": 0,
      "recent_pull_request_velocity_count": 0,
      "is_maintainer": true
    },
    {
      "id": 4,
      "open_issues": 498,
      "created_at": "2016-10-19 13:24:51.000000",
      "updated_at": "2022-08-28 22:04:29.000000",
      "first_opened_pr_at": "2022-08-28 22:04:29.000000",
      "first_pushed_commit_at": "2022-08-28 22:04:29.000000",
      "connected_at": "2022-08-28 22:04:29.000000",
      "campaign_start_date": "2022-08-28 22:04:29.000000",
      "node_id": "MDQ6VXNlcjIzNzEzMw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/237133?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/0-vortex",
      "login": "0-vortex",
      "email": "hello@opensauced.pizza",
      "is_private": false,
      "is_open_sauced_member": false,
      "is_onboarded": false,
      "is_waitlisted": false,
      "role": 10,
      "bio": "OpenSauced User",
      "blog": "https://opensauced.pizza/blog",
      "name": "MrPizza",
      "twitter_username": "saucedopen",
      "linkedin_url": "https://www.linkedin.com/in/brianldouglas",
      "github_sponsors_url": "https://github.com/sponsors/open-sauced",
      "discord_url": "https://discord.gg/opensauced",
      "company": "OpenSauced",
      "location": "San Francisco, CA",
      "display_local_time": false,
      "interests": "javascript",
      "hireable": false,
      "public_repos": 0,
      "public_gists": 0,
      "followers": 0,
      "following": 0,
      "type": "User",
      "display_email": false,
      "receive_collaboration": false,
      "receive_product_updates": false,
      "timezone": "UTC-5",
      "coupon_code": "saucy",
      "languages": "{ TypeScript: 33128, HTML: 453, JavaScript: 90, CSS: 80 }",
      "notification_count": 0,
      "insights_count": 0,
      "highlights_count": 0,
      "following_count": 0,
      "followers_count": 0,
      "recent_pull_requests_count": 0,
      "recent_pull_request_velocity_count": 0,
      "is_maintainer": true
    },
    {
      "id": 5,
      "open_issues": 498,
      "created_at": "2016-10-19 13:24:51.000000",
      "updated_at": "2022-08-28 22:04:29.000000",
      "first_opened_pr_at": "2022-08-28 22:04:29.000000",
      "first_pushed_commit_at": "2022-08-28 22:04:29.000000",
      "connected_at": "2022-08-28 22:04:29.000000",
      "campaign_start_date": "2022-08-28 22:04:29.000000",
      "node_id": "MDQ6VXNlcjIzNzEzMw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/237133?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/0-vortex",
      "login": "0-vortex",
      "email": "hello@opensauced.pizza",
      "is_private": false,
      "is_open_sauced_member": false,
      "is_onboarded": false,
      "is_waitlisted": false,
      "role": 10,
      "bio": "OpenSauced User",
      "blog": "https://opensauced.pizza/blog",
      "name": "MrPizza",
      "twitter_username": "saucedopen",
      "linkedin_url": "https://www.linkedin.com/in/brianldouglas",
      "github_sponsors_url": "https://github.com/sponsors/open-sauced",
      "discord_url": "https://discord.gg/opensauced",
      "company": "OpenSauced",
      "location": "San Francisco, CA",
      "display_local_time": false,
      "interests": "javascript",
      "hireable": false,
      "public_repos": 0,
      "public_gists": 0,
      "followers": 0,
      "following": 0,
      "type": "User",
      "display_email": false,
      "receive_collaboration": false,
      "receive_product_updates": false,
      "timezone": "UTC-5",
      "coupon_code": "saucy",
      "languages": "{ TypeScript: 33128, HTML: 453, JavaScript: 90, CSS: 80 }",
      "notification_count": 0,
      "insights_count": 0,
      "highlights_count": 0,
      "following_count": 0,
      "followers_count": 0,
      "recent_pull_requests_count": 0,
      "recent_pull_request_velocity_count": 0,
      "is_maintainer": true
    },
    {
      "id": 6,
      "open_issues": 498,
      "created_at": "2016-10-19 13:24:51.000000",
      "updated_at": "2022-08-28 22:04:29.000000",
      "first_opened_pr_at": "2022-08-28 22:04:29.000000",
      "first_pushed_commit_at": "2022-08-28 22:04:29.000000",
      "connected_at": "2022-08-28 22:04:29.000000",
      "campaign_start_date": "2022-08-28 22:04:29.000000",
      "node_id": "MDQ6VXNlcjIzNzEzMw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/237133?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/0-vortex",
      "login": "0-vortex",
      "email": "hello@opensauced.pizza",
      "is_private": false,
      "is_open_sauced_member": false,
      "is_onboarded": false,
      "is_waitlisted": false,
      "role": 10,
      "bio": "OpenSauced User",
      "blog": "https://opensauced.pizza/blog",
      "name": "MrPizza",
      "twitter_username": "saucedopen",
      "linkedin_url": "https://www.linkedin.com/in/brianldouglas",
      "github_sponsors_url": "https://github.com/sponsors/open-sauced",
      "discord_url": "https://discord.gg/opensauced",
      "company": "OpenSauced",
      "location": "San Francisco, CA",
      "display_local_time": false,
      "interests": "javascript",
      "hireable": false,
      "public_repos": 0,
      "public_gists": 0,
      "followers": 0,
      "following": 0,
      "type": "User",
      "display_email": false,
      "receive_collaboration": false,
      "receive_product_updates": false,
      "timezone": "UTC-5",
      "coupon_code": "saucy",
      "languages": "{ TypeScript: 33128, HTML: 453, JavaScript: 90, CSS: 80 }",
      "notification_count": 0,
      "insights_count": 0,
      "highlights_count": 0,
      "following_count": 0,
      "followers_count": 0,
      "recent_pull_requests_count": 0,
      "recent_pull_request_velocity_count": 0,
      "is_maintainer": false
    }
  ],
}