export const PRData = {
  "data": [
    {
      "id": 71359796,
      "user_id": 1,
      "size": 274322,
      "node_id": "MDEwOlJlcG9zaXRvcnk3MTM1OTc5Ng==",
      "git_url": "git://github.com/open-sauced/insights.git",
      "ssh_url": "git@github.com:open-sauced/insights.git",
      "clone_url": "https://github.com/open-sauced/insights.git",
      "svn_url": "https://github.com/open-sauced/insights",
      "mirror_url": null,
      "name": "open-sauced",
      "full_name": "open-sauced/insights",
      "description": "🍕This is a project to identify your next open source contribution! 🍕",
      "language": "JavaScript",
      "license": "MIT",
      "url": "https://api.github.com/repos/open-sauced/insights",
      "homepage": "https://app.opensauced.pizza",
      "topics": [
        "open-sauced",
        "open-source",
        "github"
      ],
      "open_prs_count": 5,
      "closed_prs_count": 173,
      "merged_prs_count": 27,
      "draft_prs_count": 2,
      "spam_prs_count": 2,
      "pr_velocity_count": 0,
      "pr_active_count": 0
    },
    {
      "id": 713597965,
      "user_id": 2,
      "size": 274322,
      "node_id": "MDEwOlJlcG9zaXRvcnk3MTM1OTc5Ng==",
      "git_url": "git://github.com/open-sauced/insights.git",
      "ssh_url": "git@github.com:open-sauced/insights.git",
      "clone_url": "https://github.com/open-sauced/insights.git",
      "svn_url": "https://github.com/open-sauced/insights",
      "mirror_url": null,
      "name": "open-sauced",
      "full_name": "open-sauced/insights",
      "description": "🍕This is a project to identify your next open source contribution! 🍕",
      "language": "JavaScript",
      "license": "MIT",
      "url": "https://api.github.com/repos/open-sauced/insights",
      "homepage": "https://app.opensauced.pizza",
      "topics": [
        "open-sauced",
        "open-source",
        "github"
      ],
      "open_prs_count": 5,
      "closed_prs_count": 173,
      "merged_prs_count": 2726,
      "draft_prs_count": 2,
      "spam_prs_count": 2,
      "pr_velocity_count": 0,
      "pr_active_count": 0
    },
    {
      "id": 713597966,
      "user_id": 3,
      "size": 274322,
      "node_id": "MDEwOlJlcG9zaXRvcnk3MTM1OTc5Ng==",
      "git_url": "git://github.com/open-sauced/insights.git",
      "ssh_url": "git@github.com:open-sauced/insights.git",
      "clone_url": "https://github.com/open-sauced/insights.git",
      "svn_url": "https://github.com/open-sauced/insights",
      "mirror_url": null,
      "name": "open-sauced",
      "full_name": "open-sauced/insights",
      "description": "🍕This is a project to identify your next open source contribution! 🍕",
      "language": "JavaScript",
      "license": "MIT",
      "url": "https://api.github.com/repos/open-sauced/insights",
      "homepage": "https://app.opensauced.pizza",
      "topics": [
        "open-sauced",
        "open-source",
        "github"
      ],
      "open_prs_count": 5,
      "closed_prs_count": 173,
      "merged_prs_count": 6,
      "draft_prs_count": 2,
      "spam_prs_count": 2,
      "pr_velocity_count": 0,
      "pr_active_count": 0
    },
    {
      "id": 713597967,
      "user_id": 4,
      "size": 274322,
      "node_id": "MDEwOlJlcG9zaXRvcnk3MTM1OTc5Ng==",
      "git_url": "git://github.com/open-sauced/insights.git",
      "ssh_url": "git@github.com:open-sauced/insights.git",
      "clone_url": "https://github.com/open-sauced/insights.git",
      "svn_url": "https://github.com/open-sauced/insights",
      "mirror_url": null,
      "name": "open-sauced",
      "full_name": "open-sauced/insights",
      "description": "🍕This is a project to identify your next open source contribution! 🍕",
      "language": "JavaScript",
      "license": "MIT",
      "url": "https://api.github.com/repos/open-sauced/insights",
      "homepage": "https://app.opensauced.pizza",
      "topics": [
        "open-sauced",
        "open-source",
        "github"
      ],
      "open_prs_count": 5,
      "closed_prs_count": 173,
      "merged_prs_count": 1,
      "draft_prs_count": 2,
      "spam_prs_count": 2,
      "pr_velocity_count": 0,
      "pr_active_count": 0
    },
    {
      "id": 713597968,
      "user_id": 5,
      "size": 274322,
      "node_id": "MDEwOlJlcG9zaXRvcnk3MTM1OTc5Ng==",
      "git_url": "git://github.com/open-sauced/insights.git",
      "ssh_url": "git@github.com:open-sauced/insights.git",
      "clone_url": "https://github.com/open-sauced/insights.git",
      "svn_url": "https://github.com/open-sauced/insights",
      "mirror_url": null,
      "name": "open-sauced",
      "full_name": "open-sauced/insights",
      "description": "🍕This is a project to identify your next open source contribution! 🍕",
      "language": "JavaScript",
      "license": "MIT",
      "url": "https://api.github.com/repos/open-sauced/insights",
      "homepage": "https://app.opensauced.pizza",
      "topics": [
        "open-sauced",
        "open-source",
        "github"
      ],
      "open_prs_count": 5,
      "closed_prs_count": 173,
      "merged_prs_count": 26,
      "draft_prs_count": 2,
      "spam_prs_count": 2,
      "pr_velocity_count": 0,
      "pr_active_count": 0
    },
    {
      "id": 713597968,
      "user_id": 6,
      "size": 274322,
      "node_id": "MDEwOlJlcG9zaXRvcnk3MTM1OTc5Ng==",
      "git_url": "git://github.com/open-sauced/insights.git",
      "ssh_url": "git@github.com:open-sauced/insights.git",
      "clone_url": "https://github.com/open-sauced/insights.git",
      "svn_url": "https://github.com/open-sauced/insights",
      "mirror_url": null,
      "name": "open-sauced",
      "full_name": "open-sauced/insights",
      "description": "🍕This is a project to identify your next open source contribution! 🍕",
      "language": "JavaScript",
      "license": "MIT",
      "url": "https://api.github.com/repos/open-sauced/insights",
      "homepage": "https://app.opensauced.pizza",
      "topics": [
        "open-sauced",
        "open-source",
        "github"
      ],
      "open_prs_count": 5,
      "closed_prs_count": 173,
      "merged_prs_count": 12,
      "draft_prs_count": 2,
      "spam_prs_count": 2,
      "pr_velocity_count": 0,
      "pr_active_count": 0
    }
  ],
}